### ISSUE TITLE
Update tendermint to v0.7.0

### ISSUE THREAD

**Issue by alexklho** [eris-ltd/tendermint#5]
I am experiencing some bug issues resulted from old tendermint version. I would suggest to update the tendermint component from time to time to fix some of the bugs, and they have recently released a newer version.
[https://github.com/tendermint/tendermint/releases](https://github.com/tendermint/tendermint/releases)

Would there be any plan of updating the tendermint fork?

**Comment by compleatang** [comment]
Hi Alex,

This is here only for legacy reasons. We are not planning to maintain this fork. Rather tendermint is a dependency in eris-db.

https://github.com/eris-ltd/eris-db/blob/develop/glide.yaml#L6

Indeed, we are currently using v0.6 but will be moving to v0.7 once it's more stable and well tested by us (probably in our v0.12.1)
